version: 2
registries:
  jfrog-artifactory:
    type: npm-registry
    url: "https://entur2.jfrog.io/entur2"
    token: ${{secrets.ARTIFACTORY_AUTH_TOKEN}}
updates:
- package-ecosystem: "npm"
  directory: "/"
  registries:
    - jfrog-artifactory
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
    major-updates:
      applies-to: version-updates
      update-types:
      - "major"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 2
  allow:
  - dependency-type: direct
  - dependency-type: production
